### PR TITLE
add some styles to improve UI/UX

### PR DESCRIPTION
**Pull request by z11h**

### CODE REVIEW

**Comment by xaiki** [comment]
please style it in a css file.

**Comment by z11h** [comment]
done @xaiki

**Comment by vankasteelj** [comment]
I'm just mentionning that I haven't really followed this angular project or how it's developped, but isn't there some kind of stylus/less rather than full css directly? You know, in order to build & concat at build

**Comment by NoNameProvided** [comment]
@vankasteelj yes I was wondering about this too. I was following the butter project for a while, now I want to contribute, I will come up with a ticket, describing my ideas in the next few days.

**Comment by xaiki** [comment]
`app.css` seems a better (less confusing) name than style.css

**Comment by z11h** [comment]
the stylus change has been added 😸

**Comment by z11h** [comment]
Hmm, it seems like this should be in the themes, not the actual app styles. I'll close this PR 😄

**Pull request closed without merging**
