### PR TITLE
Update for es-mx language file

### PR DESCRIPTION
**Pull request by AlbertSanIza**
Modified to be more proper and translated some english to spanish.

Still needs some changes

### CODE REVIEW

**Comment by paularchive** [comment]
Please do not update the language files yet, this will make it harder for me to fix the translation thing

**Comment by AlbertSanIza** [comment]
No problem, @paulhobbel 
I'll see on what else I might be helpfull

**Comment by paularchive** [comment]
Thanks

**Comment by xaiki** [comment]
@paulhobbel talk to @insertc0in our translation hero.

**Comment by insertc0in** [comment]
@AlbertSanIza 
Sorry but translations must be contributed via Transifex as they will eventually overwrite the existing ones on these branches. To participate in the translation project through Transifex, please go here: https://www.transifex.com/butterproject/public/

**Pull request closed without merging**
